In [1]:
import numpy as np

In [2]:
#create array of 10 zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10)[0]

0.0

In [4]:
#create array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#create array of 10 fives
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
#create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
#create an array of integers from 10 to 50 only even numbers
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
#create a 3x3 matrix wiht values range from, 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
#create a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#create random numbers from 0 to 1
np.random.rand(5)

array([0.73836231, 0.24574467, 0.43806007, 0.31394623, 0.51920099])

In [23]:
np.random.randint(10,100, size=(5))


array([80, 61, 66, 75, 47])

In [24]:
#create 5 random numbers that follow a standard normal distribution
np.random.randn(5)

array([-0.89524895,  0.43463784,  1.76975405, -0.65780129,  1.45195871])

In [27]:
np.arange(100).reshape(10,10)/100

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [30]:
#Create 20 numbers that are linearly separated ranging from 0 to 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Numpy Indexing and Selection**

In [31]:
#get the sum of all values in matrix
mat = np.arange(0,9).reshape(3,3)

In [32]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
mat.sum()

36

In [36]:
#GEt standard devaiton of values in matrix
mat.std()

2.581988897471611

In [45]:
#Get sum of all columns in matrix
mat.sum(axis=0)

array([ 9, 12, 15])

In [46]:
#Get sum of all rows in matrix
mat.sum(axis=1)

array([ 3, 12, 21])

In [38]:
matr = np.arange(30).reshape(6,5)

In [39]:
matr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [41]:
matr[0,1]

1

In [43]:
matr[2:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29]])

In [44]:
matr[0:3,2:3]

array([[ 2],
       [ 7],
       [12]])

In [51]:
#Matrix sum
mat1 = np.arange(1,45, 3).reshape(5,3)
mat2 = np.arange(1,16).reshape(5,3)

In [52]:
mat2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [50]:
mat1

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43]])

In [53]:
mat1 + mat2

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34],
       [38, 42, 46],
       [50, 54, 58]])

In [54]:
mat1 * mat2

array([[  1,   8,  21],
       [ 40,  65,  96],
       [133, 176, 225],
       [280, 341, 408],
       [481, 560, 645]])

In [55]:
mat1/mat2

array([[1.        , 2.        , 2.33333333],
       [2.5       , 2.6       , 2.66666667],
       [2.71428571, 2.75      , 2.77777778],
       [2.8       , 2.81818182, 2.83333333],
       [2.84615385, 2.85714286, 2.86666667]])

In [56]:
mat1-mat2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])