In [28]:
import numpy as np

In [ ]:
#check if all chars are numbers

In [3]:
str_data = "hello this is great"

In [4]:
print(str_data)

hello this is great


In [5]:
str_data.isalnum()

False

In [6]:
#check if all chars are alphabetic
str_data.isalpha()

False

In [7]:
"hello".isalpha()

True

In [8]:
#test if string contains digits
str_data.isnumeric()

False

In [9]:
"hello1".isnumeric()

False

In [12]:
#List Comprehension
data = [1,2,3,4]
data_sqr = [item**2 for item in data]

In [13]:
data_sqr

[1, 4, 9, 16]

In [14]:
lambda x: x**3


<function __main__.<lambda>(x)>

In [15]:
#map and Filter
data = [1,2,3,4]
y = list(map(lambda x: x**3,data ))
print(y)

[1, 8, 27, 64]


In [18]:
data = [1,2,3,4,5,6,7,8,9,10]
y = list(filter(lambda x: x%2==1, data))
print(y)

[1, 3, 5, 7, 9]


In [21]:
#grab hello from the following
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2][0])

hello


In [27]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [29]:
listdata= [1,2,3,4]
np.array(listdata)

array([1, 2, 3, 4])

In [30]:
lstoflst = [[1,2,3],[4,5,6], [7,8,9]]
np.array(lstoflst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [43]:
np.linspace(1,20, 100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.random.rand(4)

array([0.72221385, 0.26623008, 0.31964364, 0.51644154])

In [47]:
np.random.rand(2,2)

array([[0.43423868, 0.4481106 ],
       [0.96850434, 0.5025014 ]])

In [48]:
np.random.randn(3)

array([0.42869322, 0.08854398, 0.64239506])

In [49]:
np.random.randn(5,5)

array([[ 0.52873656, -0.90391937,  0.66427227, -0.96414646, -0.88960423],
       [-1.880873  ,  0.63890275, -0.62628362, -1.67008917,  0.04293867],
       [-0.34199272,  0.30949027,  0.97796923, -0.07828258, -0.80845081],
       [ 0.36973954, -0.51025464,  0.05192984, -0.42955212,  0.2678462 ],
       [ 1.00058711, -0.65444202, -0.23899916,  0.10306548, -2.22252493]])

In [50]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
np.random.randint(1,50,10)

array([17, 19,  7,  3, 27,  3, 44, 24, 29, 15])

In [52]:
arr = np.arange(25)

In [53]:
arr.shape

(25,)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [57]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [60]:
arr.dtype

dtype('int32')

In [61]:
arr = np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[8]

8

In [64]:
arr[0:4]

array([0, 1, 2, 3])

In [65]:
arr[0:4]=100

In [66]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [67]:
lstdata = [1,2,3,4,5,6,7,8]
lstdata[1:4]= 40

TypeError: can only assign an iterable

In [68]:
arr = np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
sliceofarr = arr[0:5]

In [71]:
sliceofarr

array([0, 1, 2, 3, 4])

In [72]:
sliceofarr[:]=9

In [73]:
sliceofarr

array([9, 9, 9, 9, 9])

In [74]:
arr

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [75]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
arr_2d[0]

array([ 5, 10, 15])

In [78]:
arr_2d[1]

array([20, 25, 30])

In [79]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [80]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [83]:
arr2d = np.zeros((10,10))

In [84]:
arr2d.shape

(10, 10)

In [85]:
arr2d.shape[1]

10

In [86]:
for i in range(arr2d.shape[1]):
    arr2d[i]= i

In [87]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [89]:
arr2d[[3,5,3,4]]

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [90]:
arr2d>4

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [92]:
arr = np.arange(0,10)

In [93]:
arr/arr

<ipython-input-93-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
1/arr

<ipython-input-94-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [96]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
np.max(arr)

9