In [1]:
import pandas as pd
from sklearn import preprocessing

In [3]:
import numpy as np

In [6]:
data = np.array([[12,11,10], [60,50,55],[60000, 50000, 25000]])

In [7]:
data

array([[   12,    11,    10],
       [   60,    50,    55],
       [60000, 50000, 25000]])

In [11]:
normalized_l1 = preprocessing.normalize(data, norm='l1')

In [12]:
normalized_l1

array([[0.36363636, 0.33333333, 0.3030303 ],
       [0.36363636, 0.3030303 , 0.33333333],
       [0.44444444, 0.37037037, 0.18518519]])

In [13]:
normalized_l2 = preprocessing.normalize(data, norm='l2')

In [14]:
normalized_l2

array([[0.62810871, 0.57576631, 0.52342392],
       [0.62810871, 0.52342392, 0.57576631],
       [0.73165291, 0.60971076, 0.30485538]])